# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
      time: "10:00"
    assignees:
      - "mdo2021"
      - "HaraShun"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
      time: "10:00"
    assignees:
      - "mdo2021"
    open-pull-requests-limit: 10
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      timezone: "Asia/Tokyo"
      time: "10:00"
    reviewers:
      - "mdo2021"
    open-pull-requests-limit: 10