# Generated by Django 4.2.9 on 2024-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.SlugField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
