# Generated by Django 4.2.9 on 2024-03-11 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True)),
                ('ledger_type', models.CharField(max_length=50)),
                ('num_files', models.IntegerField(default=1)),
                ('num_pages', models.IntegerField(default=1)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='business_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='closing_date',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='kana_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='kana_representative',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='representative',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='small_amount_exception',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='tax_liability',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='一般', max_length=255),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField(default=0)),
                ('page_number', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=0)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.history')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('sub_account', models.CharField(blank=True, max_length=255)),
                ('tax_class', models.CharField(blank=True, max_length=20)),
                ('keyword', models.CharField(blank=True, max_length=20)),
                ('in_use', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountItem', to='core.company')),
            ],
        ),
    ]
