# Generated by Django 4.2.9 on 2024-03-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_history_client_business_type_client_closing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', '管理者'), ('staff', '一般')], max_length=20),
        ),
    ]
