# Generated by Django 4.2.11 on 2024-03-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_result_amount_remove_result_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='num_files',
        ),
    ]
