# Generated by Django 4.2.11 on 2024-04-05 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_history_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='client',
        ),
    ]
