# Generated by Django 4.2.11 on 2024-04-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_history_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.client'),
            preserve_default=False,
        ),
    ]
